name: Docker Hub Description
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/readme.yml
jobs:
  readme:
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: codello/lilypond
        short-description: ${{ github.event.repository.description }}
