name: Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/readme.yml
jobs:
  readme:
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: codello/lilypond
